# Generated by Django 4.2.13 on 2024-10-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_post_file_data_post_file_name_post_safety_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="summary",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
